export const ErrorCodes = {
  // Common
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONFLICT: 'CONFLICT',

  // Client
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  CLIENT_ALREADY_EXISTS: 'CLIENT_ALREADY_EXISTS',
  CLIENT_SUSPENDED: 'CLIENT_SUSPENDED',

  // Module
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  MODULE_DISABLED: 'MODULE_DISABLED',

  // API (Microservice)
  API_NOT_FOUND: 'API_NOT_FOUND',
  API_DISABLED: 'API_DISABLED',
  API_DEPRECATED: 'API_DEPRECATED',

  // API Key
  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  API_KEY_EXPIRED: 'API_KEY_EXPIRED',
  INVALID_MODULE: 'INVALID_MODULE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
} as const;

export type ErrorCode = keyof typeof ErrorCodes;
